// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSiDc0-WTnIy3R5Stbvwg-37I0Bp4zjqQ',
    appId: '1:696731286076:web:b261e1f6f6993aaa0d2139',
    messagingSenderId: '696731286076',
    projectId: 'mobile-event-app-69e02',
    authDomain: 'mobile-event-app-69e02.firebaseapp.com',
    storageBucket: 'mobile-event-app-69e02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRLGJ50haqxJbecA35ODoiSCwPyvOzt8',
    appId: '1:696731286076:android:9ecffbd0f6a07e880d2139',
    messagingSenderId: '696731286076',
    projectId: 'mobile-event-app-69e02',
    storageBucket: 'mobile-event-app-69e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SDlUJT5wq70vNySKKN0evw7MDNiZlVc',
    appId: '1:696731286076:ios:dd299b86c6a4992e0d2139',
    messagingSenderId: '696731286076',
    projectId: 'mobile-event-app-69e02',
    storageBucket: 'mobile-event-app-69e02.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
